language: swift
osx_image: xcode11
xcode_project: r2-streamer-swift.xcodeproj
xcode_scheme: r2-streamer-swift
xcode_destination: platform=iOS Simulator,OS=11.3,name=iPhone X
xcode_sdk: iphonesimulator13.0

branches:
  only:
    - master
    - develop

cache:
  directories:
    - Carthage

before_install:
  - carthage update
